name: First-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world"
      - name: list items
        run: ls -lrt
      - name: print goodbye
        run: echo "Goodbye"
  
